config/routes.rb
Rails.application.routes.draw do

   get 'groups/:id/posts', to: 'posts#index', as: 'home'

  resources :photos do
    member do
      get 'code_image'
    end
  end

  resources :notifications
  resources :relationships
  resources :followings
  resources :comments

  devise_for :users, :controllers => { :registrations => "users"}

  devise_scope :user do
    root to: "devise/sessions#new"
  end
  get 'search' => 'users#index'

  resources :users do

    resources :photos do
      member do
        get 'code_image'
      end
    end

    member do
      get :following, :followers
      get 'change_password'
      post 'update_password'
      post 'update_profile_picture'
      get 'admin/group_show'
    end
    collection do
      get 'admin/user_index'
      get 'admin/group_index'

    end
    resources :notifications
  end

  resources :groups do
    member do
      post 'send_mail_on_request'
    end
    resources :user_groups
    resources :posts do
      resources :comments do
        member do
          get 'new_child'
          post 'create_child'
        end
      end
    end
  end

  resources :user_groups do
    member do
      post 'add_group_user'
    end
  end

end

app/models/following.rb
class Following < ActiveRecord::Base
end

app/controllers/followings_controller.rb
class FollowingsController < ApplicationController
  before_action :set_following, only: [:show, :edit, :update, :destroy]

  # GET /followings
  # GET /followings.json
  def index
    @followings = Following.all
  end

  # GET /followings/1
  # GET /followings/1.json
  def show
  end

  # GET /followings/new
  def new
    @following = Following.new
  end

  # GET /followings/1/edit
  def edit
  end

  # POST /followings
  # POST /followings.json
  def create
    @following = Following.new(following_params)

    respond_to do |format|
      if @following.save
        format.html { redirect_to @following, notice: 'Following was successfully created.' }
        format.json { render :show, status: :created, location: @following }
      else
        format.html { render :new }
        format.json { render json: @following.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /followings/1
  # PATCH/PUT /followings/1.json
  def update
    respond_to do |format|
      if @following.update(following_params)
        format.html { redirect_to @following, notice: 'Following was successfully updated.' }
        format.json { render :show, status: :ok, location: @following }
      else
        format.html { render :edit }
        format.json { render json: @following.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /followings/1
  # DELETE /followings/1.json
  def destroy
    @following.destroy
    respond_to do |format|
      format.html { redirect_to followings_url, notice: 'Following was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_following
      @following = Following.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def following_params
      params.require(:following).permit(:user_name, :email, :first_name)
    end
end

app/helpers/followings_helper.rb
module FollowingsHelper
end

app/views/followings/_form.html.erb
<%= form_for(@following) do |f| %>
  <% if @following.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@following.errors.count, "error") %> prohibited this following from being saved:</h2>

      <ul>
      <% @following.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_name %><br>
    <%= f.text_field :user_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/followings/edit.html.erb
<h1>Editing Following</h1>

<%= render 'form' %>

<%= link_to 'Show', @following %> |
<%= link_to 'Back', followings_path %>

app/views/followings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Followings</h1>

<table>
  <thead>
    <tr>
      <th>User name</th>
      <th>Email</th>
      <th>First name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @followings.each do |following| %>
      <tr>
        <td><%= following.user_name %></td>
        <td><%= following.email %></td>
        <td><%= following.first_name %></td>
        <td><%= link_to 'Show', following %></td>
        <td><%= link_to 'Edit', edit_following_path(following) %></td>
        <td><%= link_to 'Destroy', following, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Following', new_following_path %>

app/views/followings/new.html.erb
<h1>New Following</h1>

<%= render 'form' %>

<%= link_to 'Back', followings_path %>

app/views/followings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User name:</strong>
  <%= @following.user_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @following.email %>
</p>

<p>
  <strong>First name:</strong>
  <%= @following.first_name %>
</p>

<%= link_to 'Edit', edit_following_path(@following) %> |
<%= link_to 'Back', followings_path %>