config/routes.rb
Rails.application.routes.draw do

   get 'groups/:id/posts', to: 'posts#index', as: 'home'

  resources :photos do
    member do
      get 'code_image'
    end
  end

  resources :notifications
  resources :relationships
  resources :followings
  resources :comments

  devise_for :users, :controllers => { :registrations => "users"}

  devise_scope :user do
    root to: "devise/sessions#new"
  end
  get 'search' => 'users#index'

  resources :users do

    resources :photos do
      member do
        get 'code_image'
      end
    end

    member do
      get :following, :followers
      get 'change_password'
      post 'update_password'
      post 'update_profile_picture'
      get 'admin/group_show'
    end
    collection do
      get 'admin/user_index'
      get 'admin/group_index'

    end
    resources :notifications
  end

  resources :groups do
    member do
      post 'send_mail_on_request'
    end
    resources :user_groups
    resources :posts do
      resources :comments do
        member do
          get 'new_child'
          post 'create_child'
        end
      end
    end
  end

  resources :user_groups do
    member do
      post 'add_group_user'
    end
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :parent, class_name: "Comment"
  has_many :children, class_name: "Comment", :foreign_key => "parent_id"

  validates :message, presence: true
  validates_length_of :message, :minimum => 1, :maximum => 1000, :allow_blank => false
  after_create :user_notification_action

  #notification  to all group_users when comment is made to post
  def user_notification_action
    post = Post.find_by(id: post_id)
    group  = Group.find_by(id: post.group_id)
    group.users.each do |user|
      if self.user_id != user.id
        user.notifications.new(message:" new comment - #{message} to post #{post.message} in  #{group.name}").save
      end
    end
  end


end

app/models/following.rb
class Following < ActiveRecord::Base
end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :user_groups
  has_many :users, through: :user_groups
  has_many :posts, dependent:   :destroy

  #validates :name, presence: true
  validates_uniqueness_of :name
  validates_length_of :name, :minimum => 3, :maximum => 15, :allow_blank => false
  before_validation :strip_whitespace

  def strip_whitespace
      self.name = self.name.strip
  end

  def self.search(search)
    public_group_id = Group.find_by(name: "public").id
    if search
      search = search.downcase.strip
      where('name LIKE ? ', "%#{search}%")
    else
      all
    end
  end

end

app/models/notification.rb
class Notification < ActiveRecord::Base
	 belongs_to :user
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :user
  after_create :user_notification_action

  #notification  to user when profile picture is updated
  def user_notification_action
    @user = User.find_by(id: user_id)
    @user.following.each do |user|
      user.notifications.new(message:" #{@user.first_name} has changed profile picture.").save
    end
  end

  def image_file=(input_data)
    self.file_name = input_data.original_filename
    self.content_type = input_data.content_type.chomp
    self.binary_data = input_data.read
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :group
  has_many :comments,
    dependent:   :destroy

  validates :message, presence: true
  validates_length_of :message, :minimum => 1, :maximum => 1000, :allow_blank => false
  after_create :user_notification_action

  #notification  to all group_users when post is made in group
  def user_notification_action
    @group  = Group.find_by(id: group_id)
    @user = User.find(self.user_id)
    if @group.name == "public" then
      @user.followers.each do |user_follow|
        user_follow.notifications.new(message: "new post in #{@group.name} - #{message}").save
      end
    else
      @group.users.each do |user|
        if user.id != self.user_id
          user.notifications.new(message: "new post in #{@group.name} - #{message}").save
        end
      end
    end

  end
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base

  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

  validates :follower_id, presence: true
  validates :followed_id, presence: true
  after_create :user_notification_action

  #notification  to user when relationship is made
  def user_notification_action
    user = User.find_by(id: followed_id)
    follower = User.find_by(id: follower_id)
    user.notifications.new(message:" #{follower.first_name} is now following you.").save
  end


end

app/models/role.rb
class Role < ActiveRecord::Base
  has_many :user_roles
  has_many :users, through: :user_roles
end

app/models/user.rb
class User < ActiveRecord::Base

  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable

  has_one :user_role
  has_one :user, through: :user_role

  has_many :user_groups
  has_many :groups, through: :user_groups
  has_many :notifications
  has_many :photos
  mount_uploader :image, ImageUploader

  validates :first_name, presence: true
  validates_length_of :first_name, :minimum => 3, :maximum => 15, :allow_blank => false
  validates :last_name, presence: true
  validates_uniqueness_of :user_name
  validates_length_of :user_name, :minimum => 6, :maximum => 25, :allow_blank => false
  validates :last_name, presence: true
  validates_length_of :last_name, :minimum => 1, :maximum => 15, :allow_blank => false

  has_many :active_relationships, class_name:  "Relationship",
    foreign_key: "follower_id",
    dependent:   :destroy
  has_many :passive_relationships, class_name:  "Relationship",
    foreign_key: "followed_id",
    dependent:   :destroy

  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  before_destroy :user_destroy_action
  before_validation :strip_whitespace

  def strip_whitespace
    self.user_name = self.user_name.strip
    self.first_name = self.first_name.strip
  end

  #user is destroyed - user group,posts and commetns will be deleted
  def user_destroy_action
    user = User.find(id)
    groups.each do |group|
      if group.user_id == id
        group.destroy
      end
    end
    user.groups.each do|group|
      group.posts.each do |post|
        if post.user_id == id
          post.destroy
        end
        post.comments.each do|comment|
          if comment.user_id == id
            comment.destroy
          end
        end
      end
    end
  end

  def self.search(search)
    admin_ids = Role.find_by(role_type: "admin").user_roles.collect(&:user_id)
    if search
      search = search.downcase.strip
      where('LOWER(first_name) LIKE ? AND (id) NOT IN (?) ', "%#{search}%",  admin_ids)
    else
      where('(id) NOT IN (?)', admin_ids)
    end
  end

end

app/models/user_group.rb
class UserGroup < ActiveRecord::Base
  belongs_to :user
  belongs_to :group
end

app/models/user_role.rb
class UserRole < ActiveRecord::Base
  belongs_to :user
  belongs_to :role
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/followings_helper.rb
module FollowingsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
  def user_list
    if current_user
      admin_ids = Role.find_by(role_type: "admin").user_roles.ids
      @users = User.all.where("id != ? AND id NOT IN (?)", current_user.id , admin_ids)
      options_for_select(@users.collect{|u| [u.user_name]})
    end
  end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/user_groups_helper.rb
module UserGroupsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def role_list
    options_for_select(Role.all.collect{|u| [u.role_type]})
  end

end

app/views/admin/group_index.html.erb
<div class="admin_position">
<p id="notice"><%= notice %></p>



 <div class = "pull-right">
  <div class = "align_searchalign_search">
<%= form_tag admin_group_index_users_path, :method => 'get' do %>

 <%= text_field_tag :search, params[:search] %>
 <%= submit_tag "Search", :name => nil, class: "btn btn-sm btn-primary" %>

<% end %>
</div>
</div>

<br><br>
<div class = "post_align">

<h4>All groups</h4>
</div>
<!-- Listing all the group within apllication and user who created the group -->
   <div class = "transbox  well">
<table class = "table table-striped" >
  <thead bgcolor="#E0E0E0">
    <tr>
      <th><dl><dt>Name</dt></dl></th>
      <th><dl><dt>Created By</dt></dl></th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
  <% if @groups.first.try(:id) == nil %>
  <td colspan="3" align="center"><div class="text_">  No results found.</div></td>
  <% end %>
    <% @groups.order(created_at: :desc).each do |group| %>

    <% if group.name != "public" then %>
      <tr>
       <td><%= h group.name %></td>
       <td><%= User.find(group.user_id).first_name %></td>
       <% if group.user_id == current_user.id and current_user.user_role.role.role_type != "admin" %>
            <td><%= link_to 'Show',  group_path(group.id) %></td>
       <% else %>
           <td><%= link_to 'Show',  admin_group_show_user_path(group.id) %></td>
       <% end %>
       <td><%= link_to 'Edit', edit_group_path(group) %></td>
       <td><%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

</div>

<div class = "post_align0">
<%= paginate @groups %>
</div>
</div>

app/views/admin/group_show.html.erb
<div class="qqq">
<div class = "createGroupcreateGroup">
<br><br><br>
<p>
  <strong>Name:</strong>
  <%= @group.name %>
</p>

<p>
  <strong>Created by:</strong>
  <%= User.find(@group.user_id).first_name %>
</p>

<%= link_to 'Edit', edit_group_path(@group) %> |
<%= link_to 'Back', admin_group_index_users_path %>
<br>
<br>

<!-- List users of the group -->
<% user_group_detail = UserGroup.find_by(group_id: @group.id)
if user_group_detail != nil %>
	  <div class = "transbox  well">
<table class = "table table-striped" >
		<th colspan="2" align="center">List of users</th>
		<% @group.users.each do |user_group_detail| %>
		<tbody>
		    <tr >
				<td><%= h user_group_detail.user_name -%> </td>
				<td><%= link_to 'Destroy', user_group_path(user_id: user_group_detail.id,group_id: @group.id),
				method: :delete,
				data: { confirm: 'Are you sure?' } %></td>
			</tr>
    	</tbody>
		<% end %>
	</table>
	</div>
<% end %>

<!-- Add users to the group -->
<div class="">

<%= form_for :@group, url: add_group_user_user_group_path(@group.id) do |f| %>
	<div class ="form-group">
		<%= f.label :Users, {class: "col-sm-2 control-label"} %>
	  	<div class = "col-sm-4">
	  		<input type = "text" list = "UserList" name = "name" style="width:100px;">
      		<datalist id = "UserList"><%= user_list  %></datalist>
			<div class = "actions">
				<%= button_to('Add users ', :html => {:class => 'btn.btn-large.btn-success'})  %>
			</div>
	 	 </div>
	</div>
<% end %>
</div>



</div></div>

app/views/admin/user_index.html.erb
<div class="admin_position">
 <div class = "pull-right">
  <div class = "align_searchalign_search">
<%= form_tag admin_user_index_users_path, :method => 'get' do %>

 <%= text_field_tag :search, params[:search] %>
 <%= submit_tag "Search", :name => nil, class: "btn btn-sm btn-primary" %>

<% end %>
</div>
</div>

<br><br>
<div class = "post_align">
<h4>Listing Users</h4>
</div>
<!-- Listing all users except current user - admin -->
   <div class = "transbox  well">
<table class="table table-striped"  >
  <thead bgcolor="#E0E0E0">
    <tr>
      <td> <dl><dt>Name </dt></dl> </td>
      <td> <dl><dt> User name </dt></dl> </td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
  </thead>
  <tbody>
  <% if @users.first.try(:id) == nil %>
  <td colspan="5" align="center"><div class="text_">  No results found.</div></td>
  <% end %>
    <% @users.order(created_at: :desc).each do |user| %>
      <tr align="left">
        <td><%= h user.first_name %></td>
        <td><%= h user.user_name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<div class = "post_align0">
<%= paginate @users %>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <title>DiscussionPlatform</title>
<link href='http://fonts.googleapis.com/css?family=Ubuntu' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href='http://fonts.googleapis.com/css?family=Droid+Serif:400italic,700italic' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
    <%= render 'shared/navigation' %>
<div class="align2">
<% if current_user.present? %>
 Logged in as : <%= current_user.user_name %></li>
 <% end %>
 </div>
</head>
<body>

<% if flash[:error] then %>
<br><br>
  <div class="alert alert-dismissible alert-warning">
    <button type="button" class="close" data-dismiss="alert">×</button>
    <strong><%= flash[:error] %></p></strong>
  </div>
<%end %>

<% if flash[:notice] then %>
<br><br>
  <div class="alert alert-dismissible alert-info">
    <button type="button" class="close" data-dismiss="alert">×</button>
    <strong><%= flash[:notice] %></p></strong>
  </div>
<%end %>
  
<%= javascript_include_tag :defaults %>

<%= yield %>

</body>
</html>

app/views/layouts/user_layout.html.erb
<!DOCTYPE html>
<html>
<head>

  <title>DiscussionPlatform</title>
  <link href='http://fonts.googleapis.com/css?family=Ubuntu' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'post_before_load', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'post', 'data-turbolinks-track' => true %>

  <link href='http://fonts.googleapis.com/css?family=Droid+Serif:400italic,700italic' rel='stylesheet' type='text/css'>
 
  <%= csrf_meta_tags %>
    <%= render 'shared/navigationuser' %>
<div class ="align22">
<% if current_user.present? %>
  Logged in as : <%= current_user.user_name %>
<% end %>
</div>
</head>
<body>

<% if flash[:error] then %>
  <div class="alert alert-dismissible alert-warning">
    <button type="button" class="close" data-dismiss="alert">×</button>
    <strong><%= flash[:error] %></p></strong>
  </div>
<%end %>

<% if flash[:notice] then %>
  <div class="alert alert-dismissible alert-info">
    <button type="button" class="close" data-dismiss="alert">×</button>
    <strong><%= flash[:notice] %></p></strong>
  </div>
<%end %>
  

<%= yield %>

</body>
</html>

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Discussion Platform</a>
    </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">

        <li class="<%= 'active' if current_page?(admin_user_index_users_path) %>"><%= link_to 'All Users', admin_user_index_users_path %></li>
        <li class="<%= 'active' if current_page?(new_user_path) %>"><%= link_to 'New User', new_user_path %></li>
        <li class="<%= 'active' if current_page?(admin_group_index_users_path) %>"><%= link_to 'All Groups', admin_group_index_users_path %></li>
        <li class="<%= 'active' if current_page?(new_group_path) %>"><%= link_to 'New Group', new_group_path %></li>
        <% if current_user.present? %>
        <li><%= link_to "Logout", destroy_user_session_path, method: :delete if current_user %></li>
        <% else %>       
        <li><%= link_to "Log in", new_user_session_path,  method: :get %></li>
        <% end %>
   
        </ul>
    </div>    
</nav>

app/views/shared/_navigationuser.html.erb
<div class="navbar navbar-default" id="subnav">
    <div class="col-md-12">
        <div class="navbar-header">
           <% if current_user then %>
           
          <a href="#" style="margin-left:1px;" class="navbar-btn btn btn-primary btn-plus dropdown-toggle" data-toggle="dropdown"> Groups <b class="caret"> <small></i></small></b></i></small></a>
          <ul class="nav dropdown-menu">
            <%  if current_user.groups.try(:name) != nil then  current_user.groups.each do |user_group| %>
             <li class="<%= 'active' if current_page?(group_path(user_group)) %>"><%= link_to user_group.name, group_path(user_group) %></li>

            <% end %>
             <li class="<%= 'active' if current_page?(groups_path) %>"><%= link_to "All Groups", groups_path %></li>
             <%end end%>

          
          </ul>
         
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse2">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          </button>
      
        </div>

        <a class="navbar-brand" href="#">Discussion Platform</a>
        
      <div class="collapse navbar-collapse" id="navbar-collapse2">
   <div class="collapse navbar-collapse" id="navbar-collapse2">
          <ul class="nav navbar-nav navbar-right">
          
          <% if current_user.present? %>
          <%  count = Notification.where('user_id = ? AND created_at > ?',current_user.id, current_user.notification_time).count      
                    %>

             <li style="margin:15px 10px 0  0;"<%= 'active' if current_page?(user_notifications_path(current_user.id)) %>" ><span class="badge red"><%= link_to "Notifications #{count}", user_notifications_path(current_user.id) %></span></a></li>
              <% if current_user.present? %>
         
                    <li class="<%= 'active' if current_page?(group_posts_path(current_user.id)) %>"><%= link_to 'Home',  home_path(current_user.id) %></li>
             <% end %>
            <li class="<%= 'active' if current_page?(users_path) %>"><%= link_to 'Find Friends', users_path %></li>
              <% if current_user.present? %>
          <li class="<%= 'active' if current_page?(user_path(current_user.id)) %>"><%= link_to 'Profile', user_path(current_user.id) %></li>
          <%end%>
           <li class="<%= 'active' if current_page?(new_group_path) %>"><%= link_to 'New Group', new_group_path %></li>
           <% end %>
         
           <% if current_user.present? %>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete if current_user %></li>
            <% elsif current_page?(new_user_session_path) %>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete if current_user %></li>
          <% else %>       
             <li><%= link_to "Login", new_user_session_path,  method: :get %></li>
          <% end %>
          
            
           </ul>
        </div>  
     </div> 
</div>

</div>