config/routes.rb
Rails.application.routes.draw do

   get 'groups/:id/posts', to: 'posts#index', as: 'home'

  resources :photos do
    member do
      get 'code_image'
    end
  end

  resources :notifications
  resources :relationships
  resources :followings
  resources :comments

  devise_for :users, :controllers => { :registrations => "users"}

  devise_scope :user do
    root to: "devise/sessions#new"
  end
  get 'search' => 'users#index'

  resources :users do

    resources :photos do
      member do
        get 'code_image'
      end
    end

    member do
      get :following, :followers
      get 'change_password'
      post 'update_password'
      post 'update_profile_picture'
      get 'admin/group_show'
    end
    collection do
      get 'admin/user_index'
      get 'admin/group_index'

    end
    resources :notifications
  end

  resources :groups do
    member do
      post 'send_mail_on_request'
    end
    resources :user_groups
    resources :posts do
      resources :comments do
        member do
          get 'new_child'
          post 'create_child'
        end
      end
    end
  end

  resources :user_groups do
    member do
      post 'add_group_user'
    end
  end

end

app/models/relationship.rb
class Relationship < ActiveRecord::Base

  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

  validates :follower_id, presence: true
  validates :followed_id, presence: true
  after_create :user_notification_action

  #notification  to user when relationship is made
  def user_notification_action
    user = User.find_by(id: followed_id)
    follower = User.find_by(id: follower_id)
    user.notifications.new(message:" #{follower.first_name} is now following you.").save
  end


end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :set_relationship, only: [:show, :edit, :update, :destroy]

  # GET /relationships
  # GET /relationships.json
  def index
    @relationships = Relationship.all
  end

  # GET /relationships/1
  # GET /relationships/1.json
  def show
  end

  # GET /relationships/new
  def new
    @relationship = Relationship.new
  end

  # GET /relationships/1/edit
  def edit
  end

  # POST /relationships
  # POST /relationships.json
  def create
    @relationship = current_user.active_relationships.find_or_create_by(follower_id:  params[:follower_id], followed_id: params[:followed_id])
    if @relationship.save
      redirect_to users_path
    else
      redirect_to users_path
    end

  end

  # PATCH/PUT /relationships/1
  # PATCH/PUT /relationships/1.json
  def update
    respond_to do |format|
      if @relationship.update(relationship_params)
        format.html { redirect_to @relationship, notice: 'Relationship was successfully updated.' }
        format.json { render :show, status: :ok, location: @relationship }
      else
        format.html { render :edit }
        format.json { render json: @relationship.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /relationships/1
  # DELETE /relationships/1.json
  def destroy
    current_user.active_relationships.find(params[:id]).destroy
    redirect_to users_path
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_relationship
    @relationship = Relationship.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def relationship_params
    params.require(:relationship).permit(:follower_id, :followed_id)
  end
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/relationships/_form.html.erb
<%= form_for(@relationship) do |f| %>
  <% if @relationship.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@relationship.errors.count, "error") %> prohibited this relationship from being saved:</h2>

      <ul>
      <% @relationship.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :follower_id %><br>
    <%= f.number_field :follower_id %>
  </div>
  <div class="field">
    <%= f.label :followed_id %><br>
    <%= f.number_field :followed_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/relationships/edit.html.erb
<h1>Editing Relationship</h1>

<%= render 'form' %>

<%= link_to 'Show', @relationship %> |
<%= link_to 'Back', relationships_path %>

app/views/relationships/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Relationships</h1>

<table>
  <thead>
    <tr>
      <th>Follower</th>
      <th>Followed</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @relationships.each do |relationship| %>
      <tr>
        <td><%= relationship.follower_id %></td>
        <td><%= relationship.followed_id %></td>
        <td><%= link_to 'Show', relationship %></td>
        <td><%= link_to 'Edit', edit_relationship_path(relationship) %></td>
        <td><%= link_to 'Destroy', relationship, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Relationship', new_relationship_path %>

app/views/relationships/new.html.erb
<h1>New Relationship</h1>

<%= render 'form' %>

<%= link_to 'Back', relationships_path %>

app/views/relationships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Follower:</strong>
  <%= @relationship.follower_id %>
</p>

<p>
  <strong>Followed:</strong>
  <%= @relationship.followed_id %>
</p>

<%= link_to 'Edit', edit_relationship_path(@relationship) %> |
<%= link_to 'Back', relationships_path %>