config/routes.rb
Rails.application.routes.draw do

   get 'groups/:id/posts', to: 'posts#index', as: 'home'

  resources :photos do
    member do
      get 'code_image'
    end
  end

  resources :notifications
  resources :relationships
  resources :followings
  resources :comments

  devise_for :users, :controllers => { :registrations => "users"}

  devise_scope :user do
    root to: "devise/sessions#new"
  end
  get 'search' => 'users#index'

  resources :users do

    resources :photos do
      member do
        get 'code_image'
      end
    end

    member do
      get :following, :followers
      get 'change_password'
      post 'update_password'
      post 'update_profile_picture'
      get 'admin/group_show'
    end
    collection do
      get 'admin/user_index'
      get 'admin/group_index'

    end
    resources :notifications
  end

  resources :groups do
    member do
      post 'send_mail_on_request'
    end
    resources :user_groups
    resources :posts do
      resources :comments do
        member do
          get 'new_child'
          post 'create_child'
        end
      end
    end
  end

  resources :user_groups do
    member do
      post 'add_group_user'
    end
  end

end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :user_groups
  has_many :users, through: :user_groups
  has_many :posts, dependent:   :destroy

  #validates :name, presence: true
  validates_uniqueness_of :name
  validates_length_of :name, :minimum => 3, :maximum => 15, :allow_blank => false
  before_validation :strip_whitespace

  def strip_whitespace
      self.name = self.name.strip
  end

  def self.search(search)
    public_group_id = Group.find_by(name: "public").id
    if search
      search = search.downcase.strip
      where('name LIKE ? ', "%#{search}%")
    else
      all
    end
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  before_action :set_group, only: [:show, :edit, :update, :destroy, :send_mail_on_request]
  before_filter :authenticate_user!

  def index
    @groups = Group.all.search(params[:search]).page(params[:page]).per(10)
    authorize Group
  end

  def show
  end

  def new
    @group = Group.new
  end

  def edit
    authorize @group
  end

  # Create a group and assign user as a member of group
  def create
    @group = Group.new(group_params)
    user = User.find_by(id: current_user.id)
    @group.user_id = user.id
    respond_to do |format|
      if @group.save
        if current_user.user_role.role.role_type == "admin" then
          url_= admin_group_show_user_path(@group)
        else
          url_= group_path(@group)
        end

        user.user_groups.new(user_id: user.id ,group_id: @group.id).save
        format.html { redirect_to url_, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    authorize @group
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    authorize @group
    @group.destroy
    if (current_user.email == "admin@gmail.com")
      redirect_to admin_group_index_users_path
    else
      redirect_to user_path(current_user)

    end
  end

  #send mail on request to join group
  def send_mail_on_request
    user_created_group = User.find_by(id: @group.user_id)
    UserMailer.user_group_join_request(current_user,user_created_group,@group).deliver_now
    redirect_to group_path, notice: 'Request Mail was successfully sent.'
  end

  private

  def set_group
    @group = Group.find(params[:id])
  end

  def group_params
    params.require(:group).permit(:name, :user_ids => [])
  end

end

app/helpers/groups_helper.rb
module GroupsHelper
  def user_list
    if current_user
      admin_ids = Role.find_by(role_type: "admin").user_roles.ids
      @users = User.all.where("id != ? AND id NOT IN (?)", current_user.id , admin_ids)
      options_for_select(@users.collect{|u| [u.user_name]})
    end
  end
end

app/views/groups/_form.html.erb
<%= form_for(@group) do |f| %>

  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h4><%= pluralize(@group.errors.count, "error") %> prohibited this action:</h4>
      <ul>
        <% @group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :group %><br>
    <%= f.text_field :name, :placeholder => "enter name" %>
  </div>
  
  <div class="actions">
    <%= f.submit "Create Group", class: "btn btn-sm btn-success pull-left post-button" %>
  </div>
  
<% end %>

app/views/groups/_non_member_private_group.html.erb
 <div class ="post_align">
<p><h4>Group : <%= @group.name %></h4></p>
<p><h4>Owner : <%= User.find(@group.user_id).first_name %></h4></p>
</div>
 <div class= "align" >

<%= button_to "Join Group", { :controller => "groups", :action => "send_mail_on_request"}, class: "btn btn-sm btn-success post-button" %>

  </div>
<!-- Lsit of all memebers of the group -->
<% user_group_detail = UserGroup.find_by(group_id: @group.id)
 if user_group_detail != nil %>
  <div class="well transbox ">
    <table class="table ">
      <th><h4>List of members</h4></th>
      <% @group.users.where("user_id != ?", current_user.id).each do |user_group_detail| %>
        <tbody>
        <tr><td><dt><%= h user_group_detail.first_name -%> </dt></td>
        <% if @group.user_id == current_user.id %>
          <td><%= link_to 'delete', user_group_path(user_id: user_group_detail.id,group_id: @group.id), method: :delete, data: { confirm: 'Are you sure?' } %></td></tr>
        <% end %>
        </tbody>
      <% end %>
    </table>
  </div>
<% end %>

app/views/groups/_private_group.html.erb
<!-- Recursion for multi level comments (display and new) -->
<% def draw_tree(comment,post) %>
<% user  =User.find(comment.user_id) %>
<% photo  = Photo.find_by(user_id: user.id) %>
<br>
  <div class=" comment_align">
  <div class ="timeline-comment-header222">
  <% if user.image.current_path == nil %>

 <%= image_tag "/thumb_default.png" %>
        <% else %>
 <%= image_tag user.image_url(:thumb).to_s %>
<% end %>
 <div class = "text_"><%= link_to "#{user.first_name}", user %>  </div></div>
 <div class=" comment_align1"><%= simple_format( comment.message) %></div>
 </div>

  <div class = "align">
    <%= if comment.user_id == current_user.id then
      link_to 'delete', group_post_comment_path(@group.id,post.id,comment), method: :delete, data: { confirm: 'Are you sure?' }
    end %><br>
    <%= timeago_tag comment.created_at, :nojs => true, :limit => 10.years.ago %>
  </div>

  <div class = "sample">
    <div class = "form-group2" >
      <%= form_for :comment, url: create_child_group_post_comment_path(@group.id, post.id, comment.id) , method: :post, class: "form-horizontal" do |f| %>
      <%= f.text_field :message , class: "form-control", placeholder: "Reply" %>
      <%= f.submit "Reply", class: "btn btn-sm btn-success pull-right post-button" %>
      <% end %>
    </div>
    <a class="button1 align"> Reply</a>
      </div>

  <div class = "comment_child">
    <div class = "comment_child_display">
  <% comment.children.each do |child| %>
        <% h User.find(child.user_id).first_name %>
        <% child.message %>
   		  <ul><% draw_tree(child,post) %></ol>
        
  <% end; nil %>
</div>
<% if comment.children.first.try(:id) != nil %>
   <a class="button11 align"> View More </a>
    <a class="button12 align"> View less </a>
   <% end %>
</div>

<% end %>

<!-- List all posts with comment tree -->
<div class="well">
  <h4>Posts</h4>

 <% if @group.posts.first.try(:id) == nil %>
<br>
   <div class = "post_align">
<div class = "post_align">  
<div class = "post_align">  
<div class = "post_align">
<div class="text__"> 
 No posts in group.
 </div>
 </div></div></div></div>
 <br>
  <% end %>
  <% @group.posts.order(created_at: :desc).each do |post| %>
 

<% user  =User.find(post.user_id) %>
  <div class="well post well_post">
  
<div class = "post_align">

<div class ="timeline-comment-header1">
<div class ="timeline-comment-header222">
<% if user.image.current_path == nil %>
 <%= image_tag "/thumb_default.png" %>
        <% else %>
<%= image_tag user.image_url(:thumb).to_s %>
<%end %>
<div class = "text_"><%= link_to "#{user.first_name}", user %>  </div></div>
 <div class = "post_align1"><%=simple_format(post.message)%></div>
  
    <!-- <span class="glyphicon glyphicon-remove"></span> -->

    <div class ="align">
      <%= if post.user_id == current_user.id then
        link_to 'delete', group_post_path(@group.id,post), method: :delete, data: { confirm: 'Are you sure?' }
      end %><br>
      <%= timeago_tag post.created_at, :nojs => true, :limit => 10.years.ago %>
    </div>
   </div>
    <% post.comments.each do |comment|   
        if comment.parent_id == post.id then %>
         	<% draw_tree(comment,post) %>
				<% end 
		end %>
     </div>    
    <!-- New comment to each post -->
    <%= form_for :comment, url: group_post_comments_path(@group.id, post.id) , method: :post, class: "form-horizontal" do |f| %>
    
      <div class="form-group" style="padding:12px;" id = "comment">
        <%= f.text_field :message , class: "form-control", placeholder: "comment" %>
        <%= f.submit "Comment", class: "btn btn-sm btn-success pull-right post-button" %>
      </div>
     
    <% end %>
  </div>

  <% end %>

</div>



<!-- Lsit of all memebers of the group -->
<% user_group_detail = UserGroup.find_by(group_id: @group.id)
 if user_group_detail != nil %>
  <div class="well transbox ">
    <table class="table ">
      <th><h4>List of members</h4></th>
      <% @group.users.where("user_id != ?", current_user.id).each do |user_group_detail| %>
        <tbody>
        <tr><td><dt><%= h user_group_detail.user_name -%> </dt></td>
        <% if @group.user_id == current_user.id %>
          <td><%= link_to 'delete', user_group_path(user_id: user_group_detail.id,group_id: @group.id), method: :delete, data: { confirm: 'Are you sure?' } %></td></tr>
        <% end %>
        </tbody>
      <% end %>
    </table>
  </div>
<% end %>

app/views/groups/_public_group.html.erb
  <!-- To Do - comments diplay proper -->
  <!-- Recursion for multi level comments (display and new) -->
  <% def draw_tree(comment,post) %>
  <% user  =User.find(comment.user_id) %>
<% photo  = Photo.find_by(user_id: user.id) %>


  <div class="comment_alignalign">
<div class ="timeline-comment-header222">
<% if user.image.current_path == nil %>
    <%= image_tag "/thumb_default.png" %>
        <% else %>
 <%= image_tag user.image_url(:thumb).to_s %>
<% end %>

  <div class = "  text_"><%= link_to "#{user.first_name}", user %> </div></div>
   <div class=" comment_align2"><%= simple_format(comment.message)%> </div>
    <div class="align">

    <%= if comment.user_id == current_user.id then
         link_to 'Destroy', group_post_comment_path(@group.id,post.id,comment), method: :delete, data: { confirm: 'Are you sure?' }
                end %>
           <br>    
    <%= timeago_tag comment.created_at, :nojs => true, :limit => 10.years.ago %>
    </div>
    </div>
    <div class="sample">
    <div class="form-group2"  >
      <%= form_for :comment, url: create_child_group_post_comment_path(@group.id, post.id, comment.id) , method: :post, class: "form-horizontal" do |f| %>
      <%= f.text_field :message , class: "form-control", placeholder: "Reply" %>
      <%= f.submit "Reply", class: "btn btn-sm btn-success pull-right post-button" %>
      <% end %>
    </div>
    <a class="button1 align"> Reply</a>
    </div>
     <div class = "comment_child">
    <div class = "comment_child_display">
    <% comment.children.each do |child| %>
       <% h User.find(child.user_id).first_name %>
        <% child.message %>
          <ol><% draw_tree(child,post) %></ol>
        
    <% end; nil %></div>
    <% if comment.children.first.try(:id) != nil %>
   <a class="button11 align"> View More </a>
    <a class="button12 align"> View less </a>
   <% end %></div>
<% end %>

    <!-- List all posts with comment tree -->
    <% def display_post(posts) %>

 <% if @group.posts.first.try(:id) == nil %>
<br>
   <div class = "post_align">
<div class = "post_align">  
<div class = "post_align">  
<div class = "post_align">
<div class="text__"> 
 No posts in group.
 </div>
 </div></div></div></div>
 <br>
  <% end %>
 


    <div class="well">
    <br>
      
      <% posts.order(created_at: :desc).each do |post| %>
        <div class="well post well_post">
        <% user = User.find(post.user_id)
        photo  = Photo.find_by(user_id: user.id) 
        %>

<div class = "post_align">
<div class ="timeline-comment-header1"><div class ="timeline-comment-header222">
 <% if user.image.current_path == nil %>
      <%= image_tag "/thumb_default.png" %>
 <% else %>
    <%= image_tag user.image_url(:thumb).to_s %>
<% end %>
      
       <div class = "text_"><%= link_to "#{user.first_name}", user %> </div></div>
         <div class = "post_align2"> <%= simple_format(post.message) %></div>
         
         <div class="align">
            <%= if post.user_id == current_user.id then
            link_to 'Destroy', group_post_path(@group.id,post), method: :delete, data: { confirm: 'Are you sure?' }
            end %>
            <%= timeago_tag post.created_at, :nojs => true, :limit => 10.years.ago %>
          </div>
<br>
          </div>
              <% post.comments.each do |comment|   
                if comment.parent_id == post.id then %>
                <% draw_tree(comment,post) %>
           <% end 
        end %>
        </div>
        <br><br>
        <!-- New comment to each post -->
        <%= form_for :comment, url: group_post_comments_path(@group.id, post.id) , method: :post, class: "form-horizontal" do |f| %>
        
          <div class="form-group"  id = "comment">
            <%= f.text_field :message , class: "form-control", placeholder: "Add comment" %>
            <%= f.submit "Comment", class: "btn btn-sm btn-success pull-right post-button" %>
            </div>
            
        
        <% end %>
<br>
    </div>  
      <% end %>
  </div>
<% end %>
  
 <% user_ids = current_user.following.select(:id) %>
    <div class ="post_align"> <h4>Posts</h4></div>
    <% @posts = @group.posts.where('(user_id) in (?) or (user_id) in (?)', user_ids, current_user.id)
 display_post(@posts) %> 
 

 <!-- If current user created the group, can add other users to group -->
<% if @group.user_id == current_user.id %>
  <div class="well">
    <%= form_for :@group, url: add_group_user_user_group_path(@group.id) do |f| %>
      <div class ="form-group">
        <%= f.label :Users, {class: "col-sm-2 control-label"} %>
        <div class = "col-sm-4">
          <input type = "text" list = "UserList" name = "name" style="width:100%;">
          <datalist id = "UserList"><%= user_list %></datalist>
          <%= f.submit "Add user", class: "btn btn-success pull-right post-button" %>
        </div>
     </div>
    <% end %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<div class ="post11">
<div class=" createGroup ">
<h4>Update Group Name</h4>

<%= render 'form' %>
<br>
<% if current_user.user_role.role.role_type != "admin" %>

<%= link_to 'Back', current_user %> 
<% end %>
</div></div>

app/views/groups/index.html.erb
 <div class = "pull-right">
  <div class = "align_search33">
<%= form_tag groups_path, :method => 'get' do %>

 <%= text_field_tag :search, params[:search] %>
 <%= submit_tag "Search", :name => nil, class: "btn btn-sm btn-primary" %>

<% end %>
</div>
</div>

<br><br>
<div class = "post_align">
<h4>All groups</h4>
</div>
<!-- Listing all the group within apllication and user who created the group -->
   <div class = "transbox  well">
<table class = "table " >
  <thead bgcolor="#E0E0E0">
    <tr>
      <th><dl><dt>Name</dt></dl></th>
      <th><dl><dt>Created By</dt></dl></th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
  <% if @groups.first.try(:id) == nil %>
  <td colspan="3" align="center"><h4> No results found.</h4></td>
  <% end %>
    <% @groups.order(created_at: :desc).each do |group| %>

    <% if group.name != "public" then %>
      <tr>
       <td><%= h group.name %></td>
       <td><%= User.find(group.user_id).first_name %></td>
      
            <td><%= link_to 'Show',  group_path(group.id) %></td>
       
                 
       
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

</div>

<div class = "post_align0">
<%= paginate @groups %>
</div>

app/views/groups/new.html.erb
<div class="admin_position_new ">
<div class ="post11">
<div class=" createGroup ">
<div class = "align_to_left_">
<h4>Enter Group Detail</h4>
</div>
<%= render 'form' %>
</div>
</div>
</div>

app/views/groups/show.html.erb
<!-- Form for new post in the group -->
<% user_in_group =  current_user.groups.find_by(name: @group.name) 
if user_in_group.try(:name) %>

<% if @group.name != "public" then %>
<div class="qqq">
<div class = "createGroupcreateGroup">

<p><h4> Group : <%= @group.name %></h4></p>
<p><h4> Owner : <%= User.find(@group.user_id).first_name %></h4></p>
</div>

<!-- If current user created the group, can add other users to group -->
<% if @group.user_id == current_user.id %>
  <div class="wellwellwell">
    <%= form_for :@group, url: add_group_user_user_group_path(@group.id) do |f| %>
      <div class ="form-group">
        <%= f.label :Users, {class: "col-sm-2 control-label"} %>
        <div class = "col-sm-11">
          <input type = "text" list = "UserList" name = "name" style="width:100%;">
          <datalist id = "UserList"><%= user_list %></datalist>
          <%= f.submit "Add user", class: "btn btn-sm btn-success pull-right post-button" %>
        </div>
     </div>
    <% end %>
</div>

<% else %>
<div class ="wellwellwell">
<br>
<% user_group_detail = UserGroup.find_by(group_id: @group.id, user_id: current_user.id)
 if user_group_detail != nil %>

  <%= button_to 'Leave Group', user_group_path(user_id: user_group_detail.user_id,group_id: user_group_detail.group_id), method: :delete, data: { confirm: 'Are you sure?' } %>
 <% end %>
</div>
<% end %>
</div>


<div class="well">
  <div class="text__">What's New</div>
  <%= form_for :post, url: group_posts_path(@group.id) , method: :post, class: "form-horizontal" do |f| %>
    <div class="form-group" style="padding:12px;">
      <%= f.text_area :message, class: "form-control", placeholder: "New posts" %>
      <%= f.submit "Post", class: "btn btn-success btn-sm pull-right post-button" %>
    </div>
  <% end %>
</div>


<%= render 'private_group' %>

<% else %>
<br><br>
<div class="well">

  <div class="text__">What's New</div>
  <%= form_for :post, url: group_posts_path(@group.id) , method: :post, class: "form-horizontal" do |f| %>
    <div class="form-group" style="padding:12px;">
      <%= f.text_area :message, class: "form-control form-control", placeholder: "New posts" %>
      <%= f.submit "Post", class: "btn btn-sm btn-success pull-right post-button" %>
    </div>
  <% end %>
</div>
<%= render 'public_group' %>  

<% end %>
<% else %>
<%= render 'non_member_private_group' %>  
<% end %>